### ISSUE TITLE
Share `AlgaPattern`'s keys with `AlgaTemps`

### ISSUE THREAD

**Issue by vitreo12** [vitreo12/AlgaLib#67]
Perhaps, one wants to share the same parameter across both:
```
(
a = AP((
	def: { SinOsc.ar(\freq.kr(440)) },
	dur: 1,
	amp: AlgaTemp({ SinOsc.ar(\freq.kr(440)) }),
	freq: Pseq([440, 880], inf)
)).play
)
```

One solution for now is to use `AlgaTemp`'s `Event`:

```
(
a = AP((
	def: { SinOsc.ar(\freq.kr(440)) },
	dur: 1,
	amp: AlgaTemp((
            def: { SinOsc.ar(\freq.kr(440)) },
            freq: Pseq([440, 880], inf)
        )),
	freq: Pseq([440, 880], inf)
)).play
)
```

**Comment by vitreo12** [comment]
However, what if the user does not want to control the same keys? A new syntax to not allow it (current state) should be implemented?

**Comment by thresholdpeople** [comment]
While I think a key scoping preventing variable, or something similar, would be cool, I think it might also be fine without it, or as an even later add-on? 

What do you think of an in-between solution, instead of `AlgaTemp` being automatically aware of all external `AP` Event keys, some sort of data sharing class, similar to `Pkey`?

```
(
a = AP((
	def: { SinOsc.ar(\freq.kr(440)) },
	dur: 1,
	freq: Pseq([440, 880], inf),
	amp: AlgaTemp((
		def: { SinOsc.ar(\freq.kr(440)) },
		freq: Pkey(\freq),
	)),
)).play
)
```

**Comment by vitreo12** [comment]
This is a great solution, I like it!

I probably should link all my custom `Event` handling to more standard sharing systems like `Pkey` (which doesn't currently work in `AlgaPatterns`).

**Comment by vitreo12** [comment]
Rebased in #68
